### ISSUE TITLE
Prusaslicer encountered an error

### ISSUE THREAD

**Issue by Learoy1** [leandrolima-nyc/SnapmakerJ1#1]
<img width="1214" alt="Screenshot 2023-03-30 230541" src="https://user-images.githubusercontent.com/80989694/228974475-6dc040b1-8bf9-4769-9bd0-659d9788b3a0.png">
[10736.gcode.zip](https://github.com/leandrolima-nyc/SnapmakerJ1/files/11116537/10736.gcode.zip)

encountered an error the first time I tried to slice as shown in the screenshot. I set up as your instructions so issue with your config

**Comment by leandrolima-nyc** [comment]
<img width="800" alt="Prusa Slicer About" src="https://user-images.githubusercontent.com/70433062/229071174-bb44b5de-b2ec-447b-a304-0f9e6ead7618.png">

**Comment by leandrolima-nyc** [comment]
@Learoy1  Could you please confirm whether the issue has been fixed on your end?  If you encounter any further problems, please don't hesitate to reach out to me.  I'll be happy to assist you further.

**Comment by Learoy1** [comment]
Thanks , installed 2.6 alpha 6 and that fixed this issue, but I have another issue with both post processing scripts not working
