### ISSUE TITLE
Post-processing scripts settings present in config

### ISSUE THREAD

**Issue by evilC** [leandrolima-nyc/SnapmakerJ1#3]
The smfix and j1upload post-processing scripts are set in the print settings menu
Personally, I don't use them (I use Octoprint), so when I went to export g-code, I got the error "The configured post-processing script does not exist"
Seeing as in the documentation directs you to fill in the fields to enable smfix / j1upload, surely the config should default to not including them.
Either that, or update the documentation to direct you to delete this config if you do not need it.

**Comment by leandrolima-nyc** [comment]
Thanks for bringing this to my attention, I understand how frustrating it can be to encounter errors when trying to export G-code.

I have changed the default configuration not to include them and  I have also ensure information is clearly communicated in the updated documentation.  Appreciate the feedback.
