### ISSUE TITLE
Documentation does not direct you to click "Save current printer settings"

### ISSUE THREAD

**Issue by evilC** [leandrolima-nyc/SnapmakerJ1#4]
After you go through the documented setup process, and then exit PrusaSlicer, it prompts you to save changes to the profile.
It does not, however, seem to direct you to save printer settings.
Such that, when I was doing it, on re-opening PrusaSlicer, the config was gone.
After much fiddling around, It seems that that you need to click "Save current printer settings" to save the printer settings.
For people new to PrusaSlicer, including this in the docs would save a lot of time and head-scratching :)

**Comment by leandrolima-nyc** [comment]
You're absolutely right that PrusaSlicer prompts you to save changes to the profile but doesn't direct you to save printer settings separately.

I appreciate your feedback, and I'll make sure to include this information in the documentation to help new users save time and avoid any confusion in the future.
