### ISSUE TITLE
Bed not heating

### ISSUE THREAD

**Issue by evilC** [leandrolima-nyc/SnapmakerJ1#7]
Generated G-code:

```
M82                                                 ;absolute extrusion mode
T0



  
    G1 X-5  F6000
    M104 S200 T0           ;preheat T0
    M190 S0 C3 W2    ;wait for bed temp
```

For some reason, it's setting `M190 S0`, even though I have set the first layer bed temp to 68 and subsequent layers to 60. I have no idea what `C3 W2` is - those options do not appear to be listed on the Marlin website

**Comment by apphead** [comment]
Please export project as 3mf and attach it to your post.

**Comment by evilC** [comment]
I switched back to Dylan's config for the print I was trying to do - can I just import your INI and have both imported?
I just did this, selected your printer config, and it happened again:
[100x100x10 block - Leandro.zip](https://github.com/leandrolima-nyc/SnapmakerJ1/files/11137571/100x100x10.block.-.Leandro.zip)

**Comment by leandrolima-nyc** [comment]
@evilC, C&W are special arguments added by Snapmaker to quickly detect temperature.
C is the temperature diff
W is the detection window

**Comment by leandrolima-nyc** [comment]
@evilC 
![](https://user-images.githubusercontent.com/70433062/229940281-68e9ca3c-23c3-40f9-b31b-cae05fe0bdaf.png)

**Comment by apphead** [comment]
@evilC your 3mf contains a misconfig, that explains the 0 bed temp
![image](https://user-images.githubusercontent.com/505490/229977048-31c86320-3219-4525-a3c1-83a40ad41540.png)

![image](https://user-images.githubusercontent.com/505490/229977187-df85bcb1-320e-4660-b773-aa97c3815ea0.png)

So, just select a correct filament profile and you will be good to go.

@leandrolima-nyc : 
So C is kind of the standby temp? Or diff to what?
W detection for what? 
Can you provide a reference to help me understand?

I might need to review my [enhancement](https://github.com/leandrolima-nyc/SnapmakerJ1/issues/9)

**Comment by leandrolima-nyc** [comment]
@apphead I'm afraid I don't have any knowledge beyond the scope.  From what I understand, MacDylan originally obtained the information from the Snapmaker Cura profile and I received it from him. It appears to be something proprietary, so we're just following the established convention.  Your input and time are greatly appreciated, and I'm glad to see that improvements are being made. 

![](https://user-images.githubusercontent.com/70433062/230008514-1c194c7c-cf73-43c7-9ea0-381d62dd7efe.png)
